# multiple containers defined here
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
    - '-c'
    - |
      sed -e "s|_SCRIPT|job_download|g" deployments/dockerfile-job | tee deployments/dockerfile-job-download
      cat dockerfile-job-download
      sed -e "s|_SCRIPT|job_transpose|g" deployments/dockerfile-job | tee deployments/dockerfile-job-transpose
      cat dockerfile-job-transpose
      docker build -f deployments/dockerfile-web -t gcr.io/$PROJECT_ID/web:$COMMIT_SHA .
      docker push gcr.io/$PROJECT_ID/web:$COMMIT_SHA
      docker build -f deployments/dockerfile-job-download -t gcr.io/$PROJECT_ID/job-download:$COMMIT_SHA .
      docker push gcr.io/$PROJECT_ID/job-download:$COMMIT_SHA
      docker build -f deployments/dockerfile-job-transpose -t gcr.io/$PROJECT_ID/job-transpose:$COMMIT_SHA .
      docker push gcr.io/$PROJECT_ID/job-transpose:$COMMIT_SHA
# kubectl - deploy containers
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials --project="skynet-1984" --zone="us-central1-a" "virgo"
      sed -e "s|_COMMIT_SHA|$COMMIT_SHA|g" -e "s|_SERVICE|web|g" -e "s|_REPLICAS|1|g" deployments/workload.yaml | tee deployments/web.yaml
      cat deployments/web.yaml
      kubectl apply -f - <deployments/web.yaml
      sed -e "s|_COMMIT_SHA|$COMMIT_SHA|g" -e "s|_SERVICE|job-download|g" -e "s|_REPLICAS|0|g" deployments/workload.yaml | tee deployments/job-download.yaml
      cat deployments/job-download.yaml
      kubectl apply -f - <deployments/job-download.yaml
      sed -e "s|_COMMIT_SHA|$COMMIT_SHA|g" -e "s|_SERVICE|job-transpose|g" -e "s|_REPLICAS|0|g" deployments/workload.yaml | tee deployments/job-transpose.yaml
      cat deployments/job-transpose.yaml
      kubectl apply -f - <deployments/job-transpose.yaml
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=virgo'
