apiVersion: batch/v1
kind: Job
metadata:
  name: preprocess
  labels:
    jobgroup: preprocess
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: preprocess
      labels:
        jobgroup: preprocess
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: worker
          image: gcr.io/skynet-1984/skynet:__VERSION__
          command: ["python"]
          args: ["job_preprocess.py"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
      restartPolicy: Never