apiVersion: batch/v1
kind: Job
metadata:
  name: download
  labels:
    jobgroup: download
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: download
      labels:
        jobgroup: download
    spec:
      containers:
      - name: skynet
        image: gcr.io/skynet-1984/skynet:__VERSION__
        args: ["job_download"]
      restartPolicy: Never