apiVersion: batch/v1
kind: Job
metadata:
  name: download
  labels:
    jobgroup: download
spec:
  completions: 20
  parallelism: 20
  template:
    metadata:
      name: download
      labels:
        jobgroup: download
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: download
          image: gcr.io/skynet-1984/skynet:__VERSION__
          command: ["python"]
          args: ["job_download.py"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
            - name: TIINGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tiingo-credentials
                  key: token
      restartPolicy: Never