apiVersion: batch/v1
kind: Job
metadata:
  name: samples
  labels:
    jobgroup: samples
spec:
  completions: 20
  parallelism: 20
  template:
    metadata:
      name: samples
      labels:
        jobgroup: samples
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: samples
          image: gcr.io/skynet-1984/skynet:__VERSION__
          command: ["python"]
          args: ["job_samples.py"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
      restartPolicy: Never