apiVersion: batch/v1
kind: Job
metadata:
  name: transpose-__INDEX__
  labels:
    jobgroup: transpose
spec:
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: transpose-__INDEX__
      labels:
        jobgroup: transpose
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: transpose-__INDEX__
          image: gcr.io/skynet-1984/skynet:__VERSION__
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          command: ["python"]
          args: ["transpose.py", "__INDEX__", "__NUM_WORKERS__"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
      restartPolicy: Never