apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-web
  labels:
    app: skynet-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skynet-web
  template:
    metadata:
      labels:
        app: skynet-web
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: worker
          image: gcr.io/skynet-1984/skynet-web:__VERSION__
          command: ["flask"]
          args: ["run", "--host=0.0.0.0"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
            - name: TIINGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tiingo-credentials
                  key: token
