S_START_DATE = "1993-01-29"
S_END_DATE = "2019-12-23"
PROJECT_NAME = 'skynet-1984'
DATA_BUCKET_NAME = f'{PROJECT_NAME}-data'
DAILY_DATA_BUCKET_NAME = f"{PROJECT_NAME}-daily-data"
TEMP_BUCKET_NAME = f"{PROJECT_NAME}-tmp"