# multiple containers defined here
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
    - '-c'
    - |
      sed -e "s|_SCRIPT|job_download|g" deployments/jobs/Dockerfile | tee job-download-dockerfile
      cat Dockerfile
      docker build -f job-download-dockerfile -t gcr.io/$PROJECT_ID/job-download:$COMMIT_SHA .
      docker push gcr.io/$PROJECT_ID/job-download:$COMMIT_SHA
# kubectl - deploy containers
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials --project="skynet-1984" --zone="us-central1-a" "virgo"
      sed -e "s|_COMMIT_SHA|$COMMIT_SHA|g" -e "s|_SERVICE|job-download|g" deployments/jobs/workload.yaml | tee job-download.yaml
      cat job-download.yaml
      kubectl apply -f - <job-download.yaml
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=virgo'
