apiVersion: batch/v1
kind: Job
metadata:
  name: transpose
  labels:
    jobgroup: transpose
spec:
  completions: 20
  parallelism: 20
  template:
    metadata:
      name: transpose
      labels:
        jobgroup: transpose
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: hinton-svc-key
      containers:
        - name: worker
          image: gcr.io/skynet-1984/skynet:009f0324ce31c658cd4077594fb977159ad99406
          command: ["python"]
          args: ["job_transpose.py" "67"]
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret-volume/key
            - name: TIINGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tiingo-credentials
                  key: token
      restartPolicy: Never